!----------------------------------------------------------------------------
!    CVS:$Id: adeco_derivs.F90,v 1.9 2005/01/31 22:09:32 duse Exp $
!    CVS:$Name:  新增数值同化变量ST15n- Yangchun Xu
!    revised date: 2026/05/26
!----------------------------------------------------------------------------
module adeco_derivs
!-------------------------------------------------------------------------
! Code adapted from routines generated by 
! Tangent linear and Adjoint Model Compiler,  TAMC 5.3.2
! Modified by Jeff Dusenberry
!-------------------------------------------------------------------------
  implicit none

contains

! ***Required***
subroutine adbioderivs(istep,par,par_ifc,bio_prev,bioparams,adpar, &
       adpar_ifc,adbio_prev,addydt_bio,addydt_diag,adbioparams)
    use eco_common, only : rlt
    use grid, only : nz,nt
    use adeco_common, only : rltb
    use derivs_mod, only : derivs
    use adderivs_mod, only : DERIVS_B
    use eco_params, only : NumStateVar, NumDiagVar

    implicit none

!==============================================
! define arguments
!==============================================
    double precision, dimension(:,:) ::adbio_prev, addydt_bio, &
			addydt_diag, bio_prev

    double precision, dimension(:) :: adbioparams, adpar, bioparams, par, &
         adpar_ifc, par_ifc

    integer :: istep
  !==============================================
  ! define local variables
  !==============================================
    integer :: iz

    double precision, dimension(NumStateVar) :: dydt_fwd
    double precision, dimension(NumStateVar) :: dydt_b
    double precision, dimension(NumDiagVar)  :: diag_fwd
    double precision, dimension(NumDiagVar)  :: diag_b

!----------------------------------------------
! ROUTINE BODY
!----------------------------------------------

    do iz = nz, 1, -1
       
       rlt = par(iz)
       rltb = 0.0d0

       dydt_fwd(:) = 0.0d0
       diag_fwd(:) = 0.0d0
      
      ! 重新计算当前层正向 derivs 输出，作为 DERIVS_B 的正向输出参数
       call derivs(bio_prev(iz,:), dydt_fwd, diag_fwd, &
                   istep, iz, bioparams)

      ! 保存当前趋势项的伴随种子
       dydt_b(:) = addydt_bio(iz,:)
       diag_b(:) = addydt_diag(iz,:)

       ! 消耗伴随种子，避免后续重复使用
       addydt_bio(iz,:)  = 0.0d0
       addydt_diag(iz,:) = 0.0d0

       ! Tapenade 3.16 的正确 12 参数接口
       call DERIVS_B(bio_prev(iz,:), adbio_prev(iz,:), &
                     dydt_fwd, dydt_b, &
                     diag_fwd, diag_b, &
                     istep, iz, bioparams, adbioparams, rlt, rltb)

       ! 因为正向中 rlt = par(iz)，所以反向必须传回 adpar(iz)
       adpar(iz) = adpar(iz) + rltb
       rltb = 0.0d0

    end do


  end subroutine adbioderivs


! ***Required***
  subroutine adget_costpred(bio,diag,bioparams,adcpred,adcsed_pred,adbio, &
       addiag,adbioparams)
    use cost, only : ncnsv,xcppr,xcphy,xcchl,xczoo,xcnit,xcpo4,xcbac,xcbpr, &
                     Xcdoc,xcdon,xcdop,xcpoc,xcpon,xcpon15,xcpop,xcnfr,xcstc,xcstn,&
                     xcstn15,xcstp !Luo_MB
    use cost, only : btime_csed,etime_csed,ndat_max,ndat_sed,z_csed
    use cost, only : ndat, time_cdat, z_cdat, a_cdat
    use const, only : c0,c1,c2,secperhour,secperday
    use eco_common, only : wnsvflag
    use eco_params, only : iDETc,iNH4,iNO3,ipp,iremin,iremin_prf_n,&
                           iremin_prf_p,iMZc,mwC,mwN,mwP,numstatevar
    use eco_params, only: iPO4,iBAc,iprBAc,iSDOMc,iSDOMn,iSDOMp,&
                          iSPc,iTRc,iDDAc,iUNc,iPRTc,iDETc,iSPn,iSPp, &
		             iTRn,iTRp,iDDAn,iDDAp,iUNn,iUNp,iPRTn,iPRTp,iDETn,&
                          igrowTRnf,igrowDDAnf,igrowUNnf, &
                          iSP15n, iTR15n, iDDA15n, iUN15n,iPRT15n, &
	                   iDET15n,iepsilon_remin,iDETp,iSPchl,iTRchl,iDDAchl,iUNchl !Luo_MB
    use forcing, only : cdays
    use grid, only : nz,nt,zifc,delt,ntsout
    use eco_params, only: iwnsvo
    implicit none

!==============================================
! define arguments
!==============================================
    double precision, dimension(:,:) ::  adcsed_pred,adcpred
    double precision, dimension(:,:,:) :: bio,diag,adbio,addiag
    double precision, dimension(:) :: bioparams,adbioparams

!==============================================
! define local variables
!==============================================
    integer ised,ised_loc,idat
    integer it
    integer it2, it_temp
!double precision nsed_pred(ndat_max)
    integer, dimension(ndat_max) :: nsed_pred
    double precision t2trap
    double precision z2trap
    integer :: &
         ntsperday      , & ! number of timesteps per day
         ntsperhalfday      ! number of timesteps per half day

   double precision, dimension(numstatevar) :: wnsv,adwnsv
   double precision :: denom, epsilon_factor, exponent, exp_val, common_factor


!----------------------------------------------
! ROUTINE BODY
!----------------------------------------------
wnsv = bioparams(iwnsvo) * wnsvflag
adwnsv = 0.d0
!nsed_pred = c0
    nsed_pred = 0
    do it = 1, nt
       do ised = 1, ndat_sed(xcstc)
          ised_loc = nz+1
          if  (z_csed(xcstc,ised).lt.zifc(nz+1)) then
             do while (z_csed(xcstc,ised).lt.zifc(ised_loc))
                      ised_loc = ised_loc - 1
             end do
          endif  
          z2trap = z_csed(xcstc,ised)-zifc(ised_loc)
          t2trap = cdays(it)+z2trap/wnsv(iDETc)
          if (t2trap .gt. btime_csed(xcstc,ised) .and. &
               t2trap .le. etime_csed(xcstc,ised)) then
              !nsed_pred(ised) = nsed_pred(ised)+c1
             nsed_pred(ised) = nsed_pred(ised)+1
          endif
       end do
    end do
!where (nsed_pred(1:ndat_sed) .gt. c0)
    where (nsed_pred(1:ndat_sed(xcstc)) .gt. 0)
       adcsed_pred(xcstc,1:ndat_sed(xcstc)) = &
                adcsed_pred(xcstc,1:ndat_sed(xcstc))/nsed_pred(1:ndat_sed(xcstc))
    endwhere
    do it = nt, 1, -1
       it_temp = it
       do ised = 1, ndat_sed(xcstc)
          ised_loc = nz+1
          if  (z_csed(xcstc,ised).lt.zifc(nz+1)) then
             do while (z_csed(xcstc,ised).lt.zifc(ised_loc))
                      ised_loc = ised_loc - 1
             end do
          endif  
          z2trap = z_csed(xcstc,ised)-zifc(ised_loc)
          t2trap = cdays(it)+z2trap/wnsv(iDETc)
          if (t2trap .gt. btime_csed(xcstc,ised) .and. &
               t2trap .le. etime_csed(xcstc,ised)) then                   
             adbio(ised_loc-1,iDETc,it_temp) = adbio(ised_loc-1,iDETc,it_temp)+ &
                  adcsed_pred(xcstc,ised)*wnsv(iDETc)*mwC* &
                  exp(-(z2trap*bioparams(iremin)/max(wnsv(iDETc), 1.0d-12)))
             adbioparams(iremin) = adbioparams(iremin)- &
                  adcsed_pred(xcstc,ised)*wnsv(iDETc)*mwC* &
                  bio(ised_loc-1,iDETc,it_temp)*(z2trap/max(wnsv(iDETc), 1.0d-12))* &
                  exp(-(z2trap*bioparams(iremin)/max(wnsv(iDETc), 1.0d-12)))
             adwnsv(iDETc) = adwnsv(iDETc) + adcsed_pred(xcstc,ised)  * &
                  mwC*bio(ised_loc-1,iDETc,it_temp)* &
                  (exp(-z2trap*bioparams(iremin)/max(wnsv(iDETc), 1.0d-12)) + &
                  z2trap*bioparams(iremin)/max(wnsv(iDETc), 1.0d-12) *&
                  exp(-z2trap*bioparams(iremin)/max(wnsv(iDETc), 1.0d-12)))
          endif
       end do
    end do
    
    nsed_pred = 0
    do it = 1, nt
       do ised = 1, ndat_sed(xcstn)
          ised_loc = nz+1
          if  (z_csed(xcstn,ised).lt.zifc(nz+1)) then
             do while (z_csed(xcstn,ised).lt.zifc(ised_loc))
                      ised_loc = ised_loc - 1
             end do
          endif  
          z2trap = z_csed(xcstn,ised)-zifc(ised_loc)
          t2trap = cdays(it)+z2trap/wnsv(iDETn)
          if (t2trap .gt. btime_csed(xcstn,ised) .and. &
             t2trap .le. etime_csed(xcstn,ised)) then
              !nsed_pred(ised) = nsed_pred(ised)+c1
             nsed_pred(ised) = nsed_pred(ised)+1
          endif
       end do
    end do
!where (nsed_pred(1:ndat_sed) .gt. c0)
    where (nsed_pred(1:ndat_sed(xcstn)) .gt. 0)
       adcsed_pred(xcstn,1:ndat_sed(xcstn)) = &
                adcsed_pred(xcstn,1:ndat_sed(xcstn))/nsed_pred(1:ndat_sed(xcstn))
    endwhere

    do it = nt, 1, -1
       it_temp = it
       do ised = 1, ndat_sed(xcstn)
          ised_loc = nz+1
          if  (z_csed(xcstn,ised).lt.zifc(nz+1)) then
             do while (z_csed(xcstn,ised).lt.zifc(ised_loc))
                      ised_loc = ised_loc - 1
             end do
          endif  
          z2trap = z_csed(xcstn,ised)-zifc(ised_loc)
          t2trap = cdays(it)+z2trap/wnsv(iDETn)
          if (t2trap .gt. btime_csed(xcstn,ised) .and. &
               t2trap .le. etime_csed(xcstn,ised)) then               
             adbio(ised_loc-1,iDETn,it_temp) = adbio(ised_loc-1,iDETn,it_temp)+ &
                  adcsed_pred(xcstn,ised)*wnsv(iDETn)*mwN* &
                  exp(-(z2trap*bioparams(iremin)*bioparams(iremin_prf_n)/&
                  max(wnsv(iDETn), 1.0d-12)))
             adbioparams(iremin) = adbioparams(iremin)- &
                  adcsed_pred(xcstn,ised)*wnsv(iDETn)*mwN* &
                  bio(ised_loc-1,iDETn,it_temp)*(z2trap*&
                  bioparams(iremin_prf_n)/max(wnsv(iDETn),1.0d-12))* &
                  exp(-(z2trap*bioparams(iremin)*bioparams(iremin_prf_n)/&
                  max(wnsv(iDETn), 1.0d-12)))
             adbioparams(iremin_prf_n) = adbioparams(iremin_prf_n)- &
                  adcsed_pred(xcstn,ised)*wnsv(iDETn)*mwN* &
                  bio(ised_loc-1,iDETn,it_temp)*(z2trap*bioparams(iremin)/&
                  max(wnsv(iDETn), 1.0d-12))* &
                  exp(-(z2trap*bioparams(iremin)*bioparams(iremin_prf_n)/&
                  max(wnsv(iDETn), 1.0d-12)))
             adwnsv(iDETn) = adwnsv(iDETn) + adcsed_pred(xcstn,ised) * &
                  mwN*bio(ised_loc-1,iDETn,it_temp) * &
                  (exp(-z2trap*bioparams(iremin)*bioparams(iremin_prf_n)/&
                  max(wnsv(iDETn), 1.0d-12))  + &
                  z2trap*bioparams(iremin)*bioparams(iremin_prf_n)/&
                  max(wnsv(iDETn), 1.0d-12) * &
                  exp(-z2trap*bioparams(iremin)*bioparams(iremin_prf_n)/max(wnsv(iDETn), 1.0d-12)))
          endif
       end do
    end do
    
    !------------------------------------------------------
    ! 增加ST15n的数值同化
    !------------------------------------------------------
    
    nsed_pred = 0
    do it = 1, nt
       do ised = 1, ndat_sed(xcstn15)
          ised_loc = nz+1
          if  (z_csed(xcstn15,ised).lt.zifc(nz+1)) then
             do while (z_csed(xcstn15,ised).lt.zifc(ised_loc))
                      ised_loc = ised_loc - 1
             end do
          endif  
          z2trap = z_csed(xcstn15,ised)-zifc(ised_loc)
          t2trap = cdays(it)+z2trap/wnsv(iDET15n)
          if (t2trap .gt. btime_csed(xcstn15,ised) .and. &
               t2trap .le. etime_csed(xcstn15,ised)) then
             nsed_pred(ised) = nsed_pred(ised)+1
          endif
       end do
    end do

    where (nsed_pred(1:ndat_sed(xcstn15)) .gt. 0)
       adcsed_pred(xcstn15,1:ndat_sed(xcstn15)) = &
                adcsed_pred(xcstn15,1:ndat_sed(xcstn15))/nsed_pred(1:ndat_sed(xcstn15))
    endwhere
    do it = nt, 1, -1
       it_temp = it
       do ised = 1, ndat_sed(xcstn15)
          ised_loc = nz+1
          if  (z_csed(xcstn15,ised).lt.zifc(nz+1)) then
             do while (z_csed(xcstn15,ised).lt.zifc(ised_loc))
                      ised_loc = ised_loc - 1
             end do
          endif  
          z2trap = z_csed(xcstn15,ised)-zifc(ised_loc)
          t2trap = cdays(it)+z2trap/wnsv(iDET15n)
          if (t2trap .gt. btime_csed(xcstn15,ised) .and. &
               t2trap .le. etime_csed(xcstn15,ised)) then               
 
   	! 1. 计算共用的指数项和系数，避免重复计算和嵌套括号错误
   	! 定义分母，防止除零
	denom = wnsv(iDET15n)
	epsilon_factor = 1.0d0 - bioparams(iepsilon_remin)/1000.0d0

	exponent = -z2trap * bioparams(iremin) * &
           bioparams(iremin_prf_n) * epsilon_factor / denom

	exp_val = exp(exponent)

	! 正向量:
	! F = wnsv(iDET15n) * mwN * bio(iDET15n) * exp_val

	! 对 bio(iDET15n) 的导数
	adbio(ised_loc-1, iDET15n, it_temp) = &
     		adbio(ised_loc-1, iDET15n, it_temp) + &
    		adcsed_pred(xcstn15,ised) * wnsv(iDET15n) * mwN * exp_val

	! 公共因子：包含 bio
	common_factor = adcsed_pred(xcstn15,ised) * &
                wnsv(iDET15n) * mwN * &
                bio(ised_loc-1,iDET15n,it_temp) * exp_val

	! 对 iremin 的导数
	adbioparams(iremin) = adbioparams(iremin) - &
    		common_factor * &
     		(z2trap * bioparams(iremin_prf_n) * epsilon_factor / denom)

	! 对 iremin_prf_n 的导数
	adbioparams(iremin_prf_n) = adbioparams(iremin_prf_n) - &
     		common_factor * &
     		(z2trap * bioparams(iremin) * epsilon_factor / denom)

	! 对 iepsilon_remin 的导数
	adbioparams(iepsilon_remin) = adbioparams(iepsilon_remin) + &
     	common_factor * (z2trap * bioparams(iremin) * bioparams(iremin_prf_n) / &
     	denom / 1000.0d0)

	! 对 wnsv(iDET15n) 的导数
	adwnsv(iDET15n) = adwnsv(iDET15n) + adcsed_pred(xcstn15,ised) * mwN * &
     	bio(ised_loc-1,iDET15n,it_temp) * exp_val * (1.0d0 - exponent)
	endif

       end do
    end do


    nsed_pred = 0
    do it = 1, nt
       do ised = 1, ndat_sed(xcstp)
          ised_loc = nz+1
          if  (z_csed(xcstp,ised).lt.zifc(nz+1)) then
             do while (z_csed(xcstp,ised).lt.zifc(ised_loc))
                      ised_loc = ised_loc - 1
             end do
          endif  
          z2trap = z_csed(xcstp,ised)-zifc(ised_loc)
          t2trap = cdays(it)+z2trap/wnsv(iDETp)
          if (t2trap .gt. btime_csed(xcstp,ised) .and. &
              t2trap .le. etime_csed(xcstp,ised)) then
             !nsed_pred(ised) = nsed_pred(ised)+c1
             nsed_pred(ised) = nsed_pred(ised)+1
          endif
       end do
    end do
!where (nsed_pred(1:ndat_sed) .gt. c0)
    where (nsed_pred(1:ndat_sed(xcstp)) .gt. 0)
       adcsed_pred(xcstp,1:ndat_sed(xcstp)) = &
                adcsed_pred(xcstp,1:ndat_sed(xcstp))/nsed_pred(1:ndat_sed(xcstp))
    endwhere
    do it = nt, 1, -1
       it_temp = it
       do ised = 1, ndat_sed(xcstp)
          ised_loc = nz+1
          if  (z_csed(xcstp,ised).lt.zifc(nz+1)) then
             do while (z_csed(xcstp,ised).lt.zifc(ised_loc))
                      ised_loc = ised_loc - 1
             end do
          endif  
          z2trap = z_csed(xcstp,ised)-zifc(ised_loc)
          t2trap = cdays(it)+z2trap/wnsv(iDETp)
          if (t2trap .gt. btime_csed(xcstp,ised) .and. &
               t2trap .le. etime_csed(xcstp,ised)) then               
             adbio(ised_loc-1,iDETp,it_temp) = adbio(ised_loc-1,iDETp,it_temp)+ &
                  adcsed_pred(xcstp,ised)*wnsv(iDETp)*mwP* &
                  exp(-(z2trap*bioparams(iremin)*bioparams(iremin_prf_p)/wnsv(iDETp)))
                  !max(wnsv(iDETp), 1.0d-12)))
             adbioparams(iremin) = adbioparams(iremin)- &
                  adcsed_pred(xcstp,ised)*wnsv(iDETp)*mwP* &
                  bio(ised_loc-1,iDETp,it_temp)*(z2trap*bioparams(iremin_prf_p)/wnsv(iDETp))* &
                  exp(-(z2trap*bioparams(iremin)*bioparams(iremin_prf_p)/wnsv(iDETp)))
             adbioparams(iremin_prf_p) = adbioparams(iremin_prf_p)- &
                  adcsed_pred(xcstp,ised)*wnsv(iDETp)*mwP* &
                  bio(ised_loc-1,iDETp,it_temp)*(z2trap*bioparams(iremin)/wnsv(iDETp))* &
                  exp(-(z2trap*bioparams(iremin)*bioparams(iremin_prf_p)/wnsv(iDETp)))
		 !max(wnsv(iDETp), 1.0d-12)))
             adwnsv(iDETp) = adwnsv(iDETp) + adcsed_pred(xcstp,ised) * &
                   mwP*bio(ised_loc-1,iDETp,it_temp) * &
                  (exp(-z2trap*bioparams(iremin)*bioparams(iremin_prf_p)/wnsv(iDETp))  + &
                  z2trap*bioparams(iremin)*bioparams(iremin_prf_p)/wnsv(iDETp) * &
                  exp(-z2trap*bioparams(iremin)*bioparams(iremin_prf_p)/wnsv(iDETp)))
          endif
       end do
    end do
    
    adcsed_pred = c0
    

    ntsperday = nint(secperday/delt)
    ntsperhalfday = nint(secperday/delt/c2)

     ! Adjoint of daily mean total N2-fixation diagnostic
     
     adcpred(xcnfr,:) = adcpred(xcnfr,:) * secperday / ntsperday
     
     do idat = 1,ndat(xcnfr)
     
         do it = time_cdat(xcnfr,idat)-ntsperhalfday+ntsperday-1, &
                 time_cdat(xcnfr,idat)-ntsperhalfday, -1
     
             it_temp = it
     
             addiag(z_cdat(xcnfr,idat),igrowTRnf,it_temp) = &
                  addiag(z_cdat(xcnfr,idat),igrowTRnf,it_temp) &
                  + adcpred(xcnfr,idat)
     
             addiag(z_cdat(xcnfr,idat),igrowDDAnf,it_temp) = &
                  addiag(z_cdat(xcnfr,idat),igrowDDAnf,it_temp) &
                  + adcpred(xcnfr,idat)
     
             addiag(z_cdat(xcnfr,idat),igrowUNnf,it_temp) = &
                  addiag(z_cdat(xcnfr,idat),igrowUNnf,it_temp) &
                  + adcpred(xcnfr,idat)
     
         enddo
     
         adcpred(xcnfr,idat) = c0
     
     enddo
    
    adcpred(xcppr,:) = adcpred(xcppr,:) * secperday / ntsperday
    do idat = 1,ndat(xcppr)
        do it = time_cdat(xcppr,idat)-ntsperhalfday+ntsperday-1, &
	           time_cdat(xcppr,idat)-ntsperhalfday, -1
                   it_temp = it
		   addiag(z_cdat(xcppr, idat),iPP,it_temp) = &
		       addiag(z_cdat(xcppr, idat),iPP,it_temp) + adcpred(xcppr, idat)
        enddo 
    enddo
    
    adcpred(xcbpr,:) = adcpred(xcbpr,:) * secperday / ntsperday !Luo_MB
    do idat = 1,ndat(xcbpr)
        do it = time_cdat(xcbpr,idat)-ntsperhalfday+ntsperday-1, &
	           time_cdat(xcbpr,idat)-ntsperhalfday, -1
                   it_temp = it
		   addiag(z_cdat(xcbpr, idat),iprBAc,it_temp) = &
		       addiag(z_cdat(xcbpr, idat),iprBAc,it_temp) + adcpred(xcbpr, idat)
        enddo 
    enddo
    
    do idat = 1, ndat(xczoo)
            adbio(z_cdat(xczoo,idat), iMZc, time_cdat(xczoo,idat)) = &
               adbio(z_cdat(xczoo,idat), iMZc, time_cdat(xczoo,idat)) + adcpred(xczoo, idat)
            adcpred(xczoo, idat)  = c0   
    enddo 
    
    do idat = 1, ndat(xcnit)
           adbio(z_cdat(xcnit,idat), iNO3, time_cdat(xcnit,idat)) = &
               adbio(z_cdat(xcnit,idat), iNO3, time_cdat(xcnit,idat)) + adcpred(xcnit, idat)  
           adcpred(xcnit, idat) = c0 
    enddo 
   
    do idat = 1, ndat(xcphy)
         adbio(z_cdat(xcphy,idat), iSPn, time_cdat(xcphy,idat)) = &
               adbio(z_cdat(xcphy,idat), iSPn, time_cdat(xcphy,idat)) + adcpred(xcphy, idat)
		 adbio(z_cdat(xcphy,idat), iUNn, time_cdat(xcphy,idat)) = &
               adbio(z_cdat(xcphy,idat), iUNn, time_cdat(xcphy,idat)) + adcpred(xcphy, idat)
         adcpred(xcphy, idat) = c0
    enddo
    
    do idat = 1, ndat(xcchl)
         adbio(z_cdat(xcchl,idat), iSPchl, time_cdat(xcchl,idat)) = &
               adbio(z_cdat(xcchl,idat), iSPchl, time_cdat(xcchl,idat)) + adcpred(xcchl, idat)
         adbio(z_cdat(xcchl,idat), iTRchl, time_cdat(xcchl,idat)) = &
               adbio(z_cdat(xcchl,idat), iTRchl, time_cdat(xcchl,idat)) + adcpred(xcchl, idat) 
        adbio(z_cdat(xcchl,idat), iDDAchl, time_cdat(xcchl,idat)) = &
               adbio(z_cdat(xcchl,idat), iDDAchl, time_cdat(xcchl,idat)) + adcpred(xcchl, idat)
         adbio(z_cdat(xcchl,idat), iUNchl, time_cdat(xcchl,idat)) = &
               adbio(z_cdat(xcchl,idat), iUNchl, time_cdat(xcchl,idat)) + adcpred(xcchl, idat)
         adcpred(xcchl, idat) = c0
    enddo
    
    do idat = 1, ndat(xcpo4)
          adbio(z_cdat(xcpo4,idat), iPO4, time_cdat(xcpo4,idat)) = &
               adbio(z_cdat(xcpo4,idat), iPO4, time_cdat(xcpo4,idat)) + adcpred(xcpo4, idat)
	     adcpred(xcpo4, idat) = c0
    enddo

    do idat = 1, ndat(xcbac)
         adbio(z_cdat(xcbac,idat), iBAc, time_cdat(xcbac,idat)) = &
               adbio(z_cdat(xcbac,idat), iBAc, time_cdat(xcbac,idat)) + adcpred(xcbac, idat)
	     adcpred(xcbac, idat) = c0
    enddo 
    
    do idat = 1, ndat(xcdoc)
         adbio(z_cdat(xcdoc,idat), iSDOMc, time_cdat(xcdoc,idat)) = &
               adbio(z_cdat(xcdoc,idat), iSDOMc, time_cdat(xcdoc,idat)) + adcpred(xcdoc, idat)
	     adcpred(xcdoc, idat) = c0
    enddo 
    
    do idat = 1, ndat(xcdon)
         adbio(z_cdat(xcdon,idat), iSDOMn, time_cdat(xcdon,idat)) = &
               adbio(z_cdat(xcdon,idat), iSDOMn, time_cdat(xcdon,idat)) + adcpred(xcdon, idat)
	     adcpred(xcdon, idat) = c0
    enddo
    
    do idat = 1, ndat(xcdop)
         adbio(z_cdat(xcdop,idat), iSDOMp, time_cdat(xcdop,idat)) = &
               adbio(z_cdat(xcdop,idat), iSDOMp, time_cdat(xcdop,idat)) + adcpred(xcdop, idat)
	     adcpred(xcdop, idat) = c0
    enddo
    
    do idat = 1, ndat(xcpoc)
         adbio(z_cdat(xcpoc,idat), iSPc, time_cdat(xcpoc,idat)) = &
               adbio(z_cdat(xcpoc,idat), iSPc, time_cdat(xcpoc,idat)) + adcpred(xcpoc, idat)
         adbio(z_cdat(xcpoc,idat), iUNc, time_cdat(xcpoc,idat)) = &
               adbio(z_cdat(xcpoc,idat), iUNc, time_cdat(xcpoc,idat)) + adcpred(xcpoc, idat)
         adbio(z_cdat(xcpoc,idat), iTRc, time_cdat(xcpoc,idat)) = &
               adbio(z_cdat(xcpoc,idat), iTRc, time_cdat(xcpoc,idat)) + adcpred(xcpoc, idat)
        adbio(z_cdat(xcpoc,idat), iDDAc, time_cdat(xcpoc,idat)) = &
               adbio(z_cdat(xcpoc,idat), iDDAc, time_cdat(xcpoc,idat)) + adcpred(xcpoc, idat)
         adbio(z_cdat(xcpoc,idat), iPRTc, time_cdat(xcpoc,idat)) = &
               adbio(z_cdat(xcpoc,idat), iPRTc, time_cdat(xcpoc,idat)) + adcpred(xcpoc, idat)
         adbio(z_cdat(xcpoc,idat), iDETc, time_cdat(xcpoc,idat)) = &
               adbio(z_cdat(xcpoc,idat), iDETc, time_cdat(xcpoc,idat)) + adcpred(xcpoc, idat)    
	     adcpred(xcpoc, idat) = c0
    enddo
    
    do idat = 1, ndat(xcpon)
         adbio(z_cdat(xcpon,idat), iSPn, time_cdat(xcpon,idat)) = &
               adbio(z_cdat(xcpon,idat), iSPn, time_cdat(xcpon,idat)) + adcpred(xcpon, idat)
         adbio(z_cdat(xcpon,idat), iUNn, time_cdat(xcpon,idat)) = &
               adbio(z_cdat(xcpon,idat), iUNn, time_cdat(xcpon,idat)) + adcpred(xcpon, idat)
         adbio(z_cdat(xcpon,idat), iTRn, time_cdat(xcpon,idat)) = &
               adbio(z_cdat(xcpon,idat), iTRn, time_cdat(xcpon,idat)) + adcpred(xcpon, idat)
         adbio(z_cdat(xcpon,idat), iDDAn, time_cdat(xcpon,idat)) = &
               adbio(z_cdat(xcpon,idat), iDDAn, time_cdat(xcpon,idat)) + adcpred(xcpon, idat)
         adbio(z_cdat(xcpon,idat), iPRTn, time_cdat(xcpon,idat)) = &
               adbio(z_cdat(xcpon,idat), iPRTn, time_cdat(xcpon,idat)) + adcpred(xcpon, idat)
         adbio(z_cdat(xcpon,idat), iDETn, time_cdat(xcpon,idat)) = &
               adbio(z_cdat(xcpon,idat), iDETn, time_cdat(xcpon,idat)) + adcpred(xcpon, idat)   
	     adcpred(xcpon, idat) = c0
    enddo

   do idat = 1, ndat(xcpon15)
         adbio(z_cdat(xcpon15,idat), iSP15n, time_cdat(xcpon15,idat)) = &
               adbio(z_cdat(xcpon15,idat), iSP15n, time_cdat(xcpon15,idat)) + adcpred(xcpon15, idat)
         adbio(z_cdat(xcpon15,idat), iUN15n, time_cdat(xcpon15,idat)) = &
               adbio(z_cdat(xcpon15,idat), iUN15n, time_cdat(xcpon15,idat)) + adcpred(xcpon15, idat)
         adbio(z_cdat(xcpon15,idat), iTR15n, time_cdat(xcpon15,idat)) = &
               adbio(z_cdat(xcpon15,idat), iTR15n, time_cdat(xcpon15,idat)) + adcpred(xcpon15, idat)
         adbio(z_cdat(xcpon15,idat), iDDA15n, time_cdat(xcpon15,idat)) = &
               adbio(z_cdat(xcpon15,idat), iDDA15n, time_cdat(xcpon15,idat)) + adcpred(xcpon15, idat)
         adbio(z_cdat(xcpon15,idat), iPRT15n, time_cdat(xcpon15,idat)) = &
               adbio(z_cdat(xcpon15,idat), iPRT15n, time_cdat(xcpon15,idat)) + adcpred(xcpon15, idat)
         adbio(z_cdat(xcpon15,idat), iDET15n, time_cdat(xcpon15,idat)) = &
               adbio(z_cdat(xcpon15,idat), iDET15n, time_cdat(xcpon15,idat)) + adcpred(xcpon15, idat)   
	     adcpred(xcpon15, idat) = c0
    enddo
    
    do idat = 1, ndat(xcpop)
         adbio(z_cdat(xcpop,idat), iSPp, time_cdat(xcpop,idat)) = &
               adbio(z_cdat(xcpop,idat), iSPp, time_cdat(xcpop,idat)) + adcpred(xcpop, idat)
         adbio(z_cdat(xcpop,idat), iUNp, time_cdat(xcpop,idat)) = &
               adbio(z_cdat(xcpop,idat), iUNp, time_cdat(xcpop,idat)) + adcpred(xcpop, idat)
         adbio(z_cdat(xcpop,idat), iTRp, time_cdat(xcpop,idat)) = &
               adbio(z_cdat(xcpop,idat), iTRp, time_cdat(xcpop,idat)) + adcpred(xcpop, idat)
         adbio(z_cdat(xcpop,idat), iDDAp, time_cdat(xcpop,idat)) = &
               adbio(z_cdat(xcpop,idat), iDDAp, time_cdat(xcpop,idat)) + adcpred(xcpop, idat)
         adbio(z_cdat(xcpop,idat), iPRTp, time_cdat(xcpop,idat)) = &
               adbio(z_cdat(xcpop,idat), iPRTp, time_cdat(xcpop,idat)) + adcpred(xcpop, idat)
         adbio(z_cdat(xcpop,idat), iDETp, time_cdat(xcpop,idat)) = &
               adbio(z_cdat(xcpop,idat), iDETp, time_cdat(xcpop,idat)) + adcpred(xcpop, idat)   
	     adcpred(xcpop, idat) = c0
    enddo
    
    adbioparams(iwnsvo) = adbioparams(iwnsvo)+sum(adwnsv*wnsvflag)
    adwnsv = 0.d0
    
    adcpred = c0
    adcsed_pred = c0

  end subroutine adget_costpred



!  subroutine adbioderivs_init(bio_prev,istep,adbio_prev,adpar )
  subroutine adbioderivs_init(istep,bio_prev,diag_prev,adpar,adpar_ifc, &
       adbio_prev,addiag_prev)
    use adlight, only : adcalc_light
    use const, only : c0,p5
    use eco_params, only : iSPchl, iTRchl,iDDAchl, iUNchl
    use forcing, only : qi
    use grid, only : nz
    implicit none

!==============================================
! define arguments
!==============================================
    double precision, dimension(:,:) :: bio_prev,adbio_prev
    double precision, dimension(:,:) :: diag_prev,addiag_prev
    double precision, dimension(:) :: adpar,adpar_ifc
    integer :: istep

!==============================================
! define local variables
!==============================================
    double precision, dimension(nz) :: adchl,chl, adchl_temp, chl_temp

!----------------------------------------------
! RESET LOCAL ADJOINT VARIABLES
!----------------------------------------------
    adchl = c0
    
!----------------------------------------------
! ROUTINE BODY
!----------------------------------------------
     chl = bio_prev(:,iSPchl) + bio_prev(:,iTRchl) + bio_prev(:,iDDAchl)+ bio_prev(:,iUNchl)
 !   chl = max(chl_temp,c0)
     call adcalc_light(qi(istep),chl,adchl,adpar,adpar_ifc)
 !   adchl_temp = adchl_temp + adchl * (p5+sign(p5, chl_temp-c0))
 !   adchl = c0
    adbio_prev(:,iSPchl) = adbio_prev(:,iSPchl) + adchl
    adbio_prev(:,iTRchl) = adbio_prev(:,iTRchl) + adchl
    adbio_prev(:,iDDAchl) = adbio_prev(:,iDDAchl) + adchl
    adbio_prev(:,iUNchl) = adbio_prev(:,iUNchl) + adchl

    adchl = c0

  end subroutine adbioderivs_init

end module adeco_derivs